#!/bin/bash
cppcheck --error-exitcode=1 \
    cppcheck errorfile.c ocesql4j.c ocesql4j.h ocesqlutil.c ocesqlutil.h ppout.c \
    --enable=portability \
    --enable=performance \
    --suppress=unusedFunctions \
    --suppress=toomanyconfigs \
    --enable=style
