name: tests

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
  workflow_dispatch:
  # Run tests 10:00 PM (JST) every day
  schedule:
    - cron: '0 13 * * *'

permissions:
  contents: read

jobs:
  check-workflows:
    uses: ./.github/workflows/check-workflows.yml

  test:
    needs: check-workflows
    uses: ./.github/workflows/test.yml
  
  coverage:
    needs: check-workflows
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/coverage.yml
   
  static_analysis:
    needs: check-workflows
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/static_analysis.yml 

  doc:
    needs: check-workflows
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/doc.yml
    
  windows-build:
    needs: check-workflows
    uses: ./.github/workflows/windows-build.yml