name: doc

on:
  workflow_call:

permissions:
  contents: read

env:
  COBOL4J_LIB_DIR: /usr/lib/opensourcecobol4j
  COBOL4J_LIBCOBJ_JAR_PATH: /usr/lib/opensourcecobol4j/libcobj.jar
  OCESQL4J_LIB_DIR: /usr/lib/Open-COBOL-ESQL-4j
  OCESQL4J_OCESQL4J_JAR_PATH: /usr/lib/Open-COBOL-ESQL-4j/ocesql4j.jar
  OCESQL4J_POSTGRESQL_JAR_PATH: /usr/lib/Open-COBOL-ESQL-4j/postgresql.jar
  CLASSPATH: ":/usr/lib/Open-COBOL-ESQL-4j/ocesql4j.jar"


jobs:
  doc:
    runs-on: ubuntu-latest
    
    steps:
      # Install dependencies
      - name: Install dependencies on Ubuntu
        run: |
          sudo apt update -y
          sudo apt install -y build-essential bison flex gettext texinfo automake autoconf curl

      # Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      # Setup sbt
      - name: Setup sbt
        run: |
          curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && echo Y | ./cs setup
          echo PATH="$PATH:/home/runner/.local/share/coursier/bin" >> "$GITHUB_ENV"

      # Checkout opensource COBOL 4J
      - name: Checkout opensourcecobol 4J
        uses: actions/checkout@v4
        with:
          repository: opensourcecobol/opensourcecobol4j
          path: opensourcecobol4j
      
      # Install opensource COBOL 4J
      - name: Install opensource COBOL 4J
        working-directory: opensourcecobol4j
        run: |
          ./configure --prefix=/usr/ CFLAGS='-Werror'
          make
          sudo make install

      # Checkout
      - name: Checkout Open-COBOL-ESQL-4j
        uses: actions/checkout@v4

      # Build documentation
      - name: Build documentation
        run: |
          cp "$COBOL4J_LIBCOBJ_JAR_PATH" dblibj/lib
          sudo mkdir -p "$OCESQL4J_LIB_DIR"
          sudo curl -L -o "$OCESQL4J_POSTGRESQL_JAR_PATH" https://jdbc.postgresql.org/download/postgresql-42.2.24.jar
          sudo cp "$OCESQL4J_POSTGRESQL_JAR_PATH" dblibj/lib
          cd dblibj/
          sbt doc

      # Archive documentation 
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: dblibj-docs 
          path: dblibj/target/scala-2.13/api